### ISSUE TITLE
Remove Extra Sign-In Options

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/avalon#135]
Currently, when a user clicks the sign-in link, they see three options:
![signin.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/d1e30288-dc80-47b0-b383-f5379bcfe91e)

Ideally, the sign-in link should take you directly to the Shibboleth, and the other methods would not work. Alternately, the Select Sign In Method page would still exist, but only one option would be present, for Shibboleth.

**Comment by devanshu-m** [comment]
PR: https://github.com/emory-libraries/avalon/pull/138

Removing duplicate saml config from settings yaml will take the user directly to shib, since we do not have any other sign in methods. This config is already present in `authentication.rb` file.
No screenshot to present. When this gets deployed, clicking sign in will take the user directly to shib.

**Comment by libdgg** [comment]
CB approves

**Comment by devanshu-m** [comment]
When I clicked on sign in on prod, I was directly taken to shib, as expected. Closing.
