### ISSUE TITLE
Determine scope of minimal branding (Emory Logo, other?)

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#26]

**Comment by lovinscari** [comment]
@rotated8 Can you please review this ticket to ensure I captured all information from our meeting?

**Comment by rotated8** [comment]
@lovinscari I don't see a description on this ticket, so I created #86 as a first step. This is a good ticket for our discussion with Rosy.

**Comment by libdgg** [comment]
Meeting 10-01-2020 RM, WU, BW, CB, CL, DG

- Review of Will's work. Header and footer. Possible links are Ares and Canvas (possibly in utility bar and/or footer)
- The goal of the site is the individual item page (less about the home page and searching).
- On the item page we may not want the search box. There are some questions about whether a student would be able to browse to other films they have access to or if they wouldn't be able to see other content without coming from Canvas
- Rosalyn will do a mockup of the header and will check in with Maria and Jon at Indiana about things.
- Need to explore Create Timeline feature
- Need to look at Collections
- Software Engineering can explore a student user to see how the interface/features display to determine where we can focus time and energy on what to customize. Also look at the ability to get a branch into the test instance in the unrestricted. Collin with put this work into ZenHub tickets.

**Comment by wulman16** [comment]
@rosy1280 In order to make a wireframe/mockup, do you need a version of Avalon deployed with the Lux header and footer I showed last week? I have a couple of screenshots below for reference, so if that's all you need from me, I will wait until we have a wireframe before making a PR for any header/footer work.

![Screen Shot 2020-10-08 at 11.42.58 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/a4e7f756-18d2-4b4e-99b1-b4abc07457a5)

![Screen Shot 2020-10-08 at 11.43.06 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/869a1dcc-9010-470d-8bb4-7cb5028dfc00)

**Comment by rosy1280** [comment]
connecting with James Steffen to see what he thinks about links in the footer.  

@wulman16 the logo you used in the above screenshot should replace the existing Avalon logo.  I like the color changes you made in the most recent deploy:

<img width="1249" alt="Screen Shot 2020-10-09 at 3 10 48 PM" src="https://user-images.githubusercontent.com/143322/95622498-9f7f3c80-0a41-11eb-9fd7-ee857339a62c.png">

to determine if we need something more robust for the navigation, i think i'm going to need to see how things work when integrated with canvas.

**Comment by wulman16** [comment]
Thanks @rosy1280. I'll go ahead and make a ticket to replace the logo in the header.

**Comment by libdgg** [comment]
@lovinscari Please  update this ticket with any action items or next steps to accompany the assignment to Rosalyn.

**Comment by rosy1280** [comment]
I've turned this into an Epic and will add a few tickets to it based on the work i see that needs to be done around branding.

**Comment by libdgg** [comment]
@rosy1280 Do you have any other questions, concerns or preferences with header/footer or branding? If not, are you ok with us closing this epic?

**Comment by rosy1280** [comment]
@libdgg I do have questions, concerns, and preferences with changes to the header/footer but I'm unable to identify what those changes should be until the Canvas LTI is integrated.  Has that been done?  Is there test content that I can access as a student via Canvas so that I can start to flesh this Epic out with further tickets?

**Comment by rotated8** [comment]
@rosy1280 Thank you for reminding me of that. That work (and supporting work around shibboleth for people adding content to Avalon) is ongoing, (#46 and #40). I'll add those ad blockers on this ticket, and ping you when this is ready to move forward again.

**Comment by libdgg** [comment]
Tickets related to Avalon 7.2 have closed #107, #122 and #124
