### ISSUE TITLE
 Clone avalon repo and get tests passing locally

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#70]
1. Clone our fork of Avalon (https://github.com/emory-libraries/avalon)
2. Get your development environment working, either with Docker (recommended) or by setting up the dependencies locally. More info is in the README.
3. Successfully run the test suite.

When you complete avalon setup and test suite is green, please check your name:
- [x] Zo
- [x] Brad
- [x] Collin
- [x] Will
- [x] Devanshu

**Comment by rotated8** [comment]
@lovinscari @doug FYI- the estimate here includes time for everyone, not for a single person.

**Comment by bwatson78** [comment]
Have to hold off until new Mac arrives.

**Comment by lovinscari** [comment]
Update from Devanshu "Standup updates:
Today: worked on setting up avalon locally and making sure test suite is green. continuing to work on the same."

**Comment by lovinscari** [comment]
Order was placed for Brad's laptop but it will not arrive until 9/18/20 after which he can make an appointment with Linda. SE Team in general was able to complete work so we will remove Brad for a new ticket after 9/18/20

**Comment by rotated8** [comment]
@lovinscari FYI: @bwatson78 Brad has not been able to get the full test suite to run, but I feel if he can get part of it working, we can rely on CircleCI to take care of the rest for us. During development, Brad will only need to run his tests, rather than the full suite. If he can get part of the suite running, I'd be happy for him to check off his task here and we can close this ticket.
