### ISSUE TITLE
Test streaming from unrestricted AWS

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#79]
Solomon will attempt to import a video and then stream. Then let the team know and we can all confirm streaming.

**Comment by libdgg** [comment]
Solomon did a test and it failed.

**Comment by lovinscari** [comment]
SH - Still not able to get this work. Created an admin user account but just gets a message that it failed. He was just looking at this from the front-end perspective. Download was a short MP4 file. SH - Suggest assigning this to Mark or Ann. DG will review with Mark and Ann to get their thoughts on next steps.

**Comment by libdgg** [comment]
Now that the multi-environment issue is worked out, Mark and Ann can proceed with doing some tests of video streaming in their environments.

**Comment by libdgg** [comment]
AH uploaded video (but it is not streaming). May be a permissions issue. One error message uploading w/o transcoding "did not have access to temp" S3. You can see the thumbnails and click on the link but it is blank.

**Comment by lovinscari** [comment]
Ann is out on 9/14 but sent an update on Saturday.

**Comment by libdgg** [comment]
Per Ann in slack Saturday 9/12

Just an FYI re: ingesting content: 
I uploaded a few videos from the Internet Archive (either Open Access or Public Domain). You can search and browse. 
https://arch.emoryavalon.com/catalog?q=&search_field=all_fields&utf8=%E2%9C%93
Scenario 1: 
They seem to go through the process and you can see the thumbnail and video time, but when you click on the video you get a blank screen. If I go into the dropbox in AWS, the videos are there.  
Scenario 2: 
The second scenario is where I uploaded a video “Bits and Bytes”, and checked the box to skip encoding. That’s when I see an error message:
  ERROR: /tmp/Episode_01_Getting_Started.mp420200912-1-suj6i3 does not exist or is not accessible (edited)

**Comment by lovinscari** [comment]
Mark and Ann are having similar issues with uploading videos but not being able to view. Local instance installed by Ann shows the application is not transcoding.

**Comment by libdgg** [comment]
FFMPEG may be used by Avalon but with Avalon Terraform it is using AWS elastic transcoder? May need more investigation.

**Comment by mprefer** [comment]
Found this error in Sidekiq when trying to transcode an MP4 file:

![Avalon_Encoder_Error.png](https://images.zenhubusercontent.com/5c12be5f7387c610cbb20714/e3a3c7a2-0172-49b5-8d20-496f8c47b9df)

**Comment by libah** [comment]
I was able to transcode an mp4 file directly using AWS Elastic Transcoder. So the transcoder itself is working. 
https://stack1-arch-derivatives.s3.amazonaws.com/.mp4

**Comment by lovinscari** [comment]
Solomon is going to look at permissions between the transcoder and Avalon.

**Comment by mprefer** [comment]
After performing a "git pull" on the Terraform repo to update the changes that Solomon made per Phoung, I did a "terraform destroy",
then performed a "terraform apply".
After the systems was ready, I could transcode an .mp3 file and an .mp4 file.
The Elastic Transcoder pipeline indicate that jobs had run successfully and file showed up in the derivatives folder.
I could playback the .mps audio file, but the .mp4 file was munged. 
Processing a different .mp4 now.

**Comment by SolomonHD** [comment]
After contacting Phuong we've fixed the issue.

The problem was that the Transcoding Pipeline needs avalon "presets" and most were missing. The command to create the presets was broken on develop and master branches, Phuong created a branch called `et-sdk-3` on the main avalon repo to fix this issue. I had to rebuild CodeBuild docker repo while pointing to the correct repo and branch.

The following screenshot shows how many avalon presets there are supposed to be, before we only had 3 audio presets.
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/38a17ec1-3c1d-4ad0-85ea-f1a3c62ef9a5)

The command to generate the presets is `rake avalon:aws:create_presets`
or `docker exec -it avalon-docker-aws_min_avalon_1 rake avalon:aws:create_presets` from outside the container. I believe this only needs to be done once, not per environment.

Additionally I noticed another bug where it will not transcode the file if certain special characters are present. What caused the error for me was a file with the `[]` characters.

Finally there was another error that if you create a collection but do not provide Title or Date, and then upload a video to the collection, then try to publish the video it will show an error screen.

**Comment by libdgg** [comment]
I can’t sign in to test the streaming video. I get an “invalid username or email or password”. Can you confirm the credentials?

https://test.emoryavalon.com/media_objects/0g354f20t
Username = user@example
password = password

We should also confirming the current state (and next steps) for the following:
- This doesn't load: https://prod.emoryavalon.com/
- This site loads but doesn't have videos: https://test.emoryavalon.com/
- This site loads, has videos, but they aren't streaming: https://test.emoryavalon.com/

**Comment by SolomonHD** [comment]
FYI I ran into the same issue when building the restricted account. The emory library version of avalon still doesn't have the fixes in place to generate presets. I had to build from the main avalon develop branch.
