### ISSUE TITLE
Improve the Footer

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/avalon#86]
In the footer, remove Avalon logo, website, and contact us
Format footer to match Emory Digital Collections site. Include the following links:
- About Course Reserves - https://libraries.emory.edu/materials/course-reserves.html
- Copyright Information - https://libraries.emory.edu/using-the-library/reserves-copyright.html
- Ask a Librarian - http://emory.libanswers.com/
- Donate - https://libraries.emory.edu/about/support-emory-libraries/index.html
- Include information about Avalon version number where we currently have Emory Digital Collections version info
- Leave all other things the same

Current footer:
![avalon-footer.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/06807228-4afb-48f9-aa52-5f184d3d3b99)

Digital footer:
![digital-footer.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/e9de81a6-5ee9-4af2-9555-dbfa5a222cb7)

**Comment by wulman16** [comment]
A branch with the Emory header and footer replacing the default Avalon header and footer: https://github.com/emory-libraries/avalon/tree/header-footer-styling

**Comment by lovinscari** [comment]
Move to blocked pending outcome of overall branding requirements after restricted environments are setups

**Comment by libdgg** [comment]
NOTE: pending review from Rosalyn as part of ticket #26

**Comment by rosy1280** [comment]
Decisions from Avalon UI Review:

* In the header, remove search box
* In the header, instead of showing the "user name" show "You are currently signed in"
* In the footer, remove Avalon logo, website, and contact us
* Format footer to match Emory Digital Collections site.  Include the following links:
   - About Course Reserves - https://libraries.emory.edu/materials/course-reserves.html
   - Copyright Information - 
   - Ask a Librarian - http://emory.libanswers.com/
   - Donate - https://libraries.emory.edu/about/support-emory-libraries/index.html

**Comment by rotated8** [comment]
@rosy1280 @libdgg I split the header work out into other tickets, #132 and #133, and have copied the details from the comment into the body of the ticket.

**Comment by alexBLR** [comment]
![Screen Shot 2021-01-04 at 10.44.03 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/1cf618ab-44f4-49a6-9be2-a61c4a301daf)
